server:
  port: 8081

#自定义配置，心情语录
my:
  mood:
    today: 周末
    content: 期待周末
    author: "夏企博"

    # 功能开关
  feature:
    helloSwitch: true
    closeMsg: "该接口正在维护，10分钟后再来吧！"



xia:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c401991cbfb814207c
      accountToken: 44c525ed51df4240b65d736b1e85994d
      appId: 2c94811c9860a9c401991cbfb9842083
      templateId: 1